# Generated by Django 5.1.5 on 2025-05-10 03:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='moved_to_pharmacy_date',
            field=models.DateField(blank=True, help_text='Date when product was moved to pharmacy section', null=True, verbose_name='Moved to Pharmacy Date'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='original_quantity',
            field=models.IntegerField(default=0, help_text='Initial quantity when product was added', verbose_name='Original Quantity'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reserved_quantity',
            field=models.IntegerField(default=0, help_text='Quantity reserved during payment'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('expired', 'Expired'), ('disposed', 'Disposed'), ('quarantined', 'Quarantined')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_disposed',
            field=models.IntegerField(default=0, help_text='Sum of all disposed quantities', verbose_name='Total Disposed'),
        ),
        migrations.CreateModel(
            name='Disposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField(default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('incineration', 'Incineration'), ('landfill', 'Sanitary Landfill'), ('return', 'Returned to Manufacturer'), ('other', 'Other Method')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('documentation', models.FileField(blank=True, null=True, upload_to='disposals/%Y/%m/%d/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documented_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals_documented', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory')),
                ('witnessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals_witnessed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('loan_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('quantity_loaned', models.IntegerField()),
                ('quantity_returned', models.IntegerField(default=0)),
                ('quantity_sold', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('on_loan', 'On Loan to Pharmacy'), ('returned', 'Returned to Warehouse'), ('sold', 'Sold by Pharmacy')], default='on_loan', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_sales', to='inventory.inventory')),
            ],
        ),
        migrations.DeleteModel(
            name='ReservedInventory',
        ),
    ]
