# Generated by Django 5.1.5 on 2025-05-12 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_transaction_alter_sale_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cart',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_ref',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
