# Generated by Django 5.1.5 on 2025-04-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_temp_email_customer_verification_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved - Pending Verification'), ('rejected', 'Rejected'), ('verified', 'Verified - Active')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='temp_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
