# Generated by Django 5.1.5 on 2025-04-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customer_is_superuser_alter_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
