# Generated by Django 5.1.5 on 2025-04-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.CharField(blank=True, choices=[('clerk', 'Clerk'), ('manager', 'Manager'), ('admin', 'Admin'), ('finance', 'Finance'), ('regulatory', 'Regulatory')], default=None, max_length=50, null=True),
        ),
    ]
