# Generated by Django 5.1.5 on 2025-04-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('clerk', 'Clerk'), ('manager', 'Manager'), ('admin', 'Admin'), ('finance', 'Finance'), ('regulatory', 'Regulatory')], default=None, max_length=20),
        ),
    ]
