# Generated by Django 5.1.5 on 2025-04-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(choices=[('antibiotics', 'Antibiotics'), ('pain_relievers', 'Pain Relievers (Analgesics)'), ('anti_inflammatory', 'Antipyretics and Anti-inflammatory Drugs'), ('gastrointestinal', 'Antacids and Gastrointestinal Medicines'), ('vitamins', 'Vitamins and Supplements'), ('antidiabetics', 'Antidiabetics'), ('cardiovascular', 'Cardiovascular Medicines'), ('respiratory', 'Respiratory Medicines (Asthma, COPD)'), ('antimalarials', 'Antimalarials'), ('cough_cold', 'Cough and Cold Preparations')], default='antibiotics', max_length=50, verbose_name='Category'),
        ),
    ]
