# Generated by Django 5.1.5 on 2025-04-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_options_alter_inventory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='moved_to_pharmacy_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('available', 'Available in Main Storage'), ('pharmacy', 'Moved to Pharmacy'), ('sold', 'Sold'), ('expired', 'Expired')], default='available', max_length=20),
        ),
    ]
