# Generated by Django 5.1.5 on 2025-04-29 11:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_moved_to_pharmacy_date_inventory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_date', models.DateField(default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('incineration', 'Incineration'), ('landfill', 'Sanitary Landfill'), ('return', 'Returned to Manufacturer'), ('other', 'Other Method')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('documentation', models.FileField(blank=True, null=True, upload_to='disposals/%Y/%m/%d/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documented_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals_documented', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory')),
                ('witnessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals_witnessed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
