# Generated by Django 5.1.5 on 2025-04-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_disposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposal',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
