# Generated by Django 5.1.5 on 2025-04-29 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_disposal_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='original_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DisposalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_disposed', models.IntegerField()),
                ('remaining_quantity', models.IntegerField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('disposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.disposal')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposal_records', to='inventory.inventory')),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
    ]
