# Generated by Django 5.1.5 on 2025-04-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventory_original_quantity_disposalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposal',
            name='total_disposed',
            field=models.IntegerField(default=0),
        ),
    ]
