# Generated by Django 5.1.5 on 2025-04-29 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_disposal_total_disposed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disposal',
            options={'ordering': ['-disposal_date'], 'verbose_name_plural': 'Disposals'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['expiry_date'], 'verbose_name_plural': 'Inventory'},
        ),
        migrations.RemoveField(
            model_name='disposal',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='disposal',
            name='total_disposed',
        ),
        migrations.AlterField(
            model_name='disposal',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='original_quantity',
            field=models.IntegerField(help_text='Initial quantity when product was added', verbose_name='Original Quantity'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(help_text='Current quantity in inventory', verbose_name='Current Quantity'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='shelf_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shelf Location'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('available', 'Available in Main Storage'), ('pharmacy', 'Moved to Pharmacy'), ('sold', 'Sold'), ('expired', 'Expired'), ('disposed', 'Disposed')], default='available', max_length=20),
        ),
        migrations.DeleteModel(
            name='DisposalRecord',
        ),
    ]
