# Generated by Django 5.1.5 on 2025-04-29 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_disposal_options_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disposal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='moved_to_pharmacy_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='original_quantity',
        ),
        migrations.AlterField(
            model_name='disposal',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='shelf_location',
            field=models.CharField(blank=True, help_text='Physical location of the product in storage', max_length=100, null=True, verbose_name='Shelf Location'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('expired', 'Expired'), ('disposed', 'Disposed'), ('quarantined', 'Quarantined')], default='available', max_length=20),
        ),
    ]
