# Generated by Django 5.1.5 on 2025-04-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_disposal_options_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='moved_to_pharmacy_date',
            field=models.DateField(blank=True, help_text='Date when product was moved to pharmacy section', null=True, verbose_name='Moved to Pharmacy Date'),
        ),
    ]
