# Generated by Django 5.1.5 on 2025-04-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_inventory_moved_to_pharmacy_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='original_quantity',
            field=models.IntegerField(default=0, help_text='Initial quantity when product was added', verbose_name='Original Quantity'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_disposed',
            field=models.IntegerField(default=0, help_text='Sum of all disposed quantities', verbose_name='Total Disposed'),
        ),
    ]
