# Generated by Django 5.1.5 on 2025-04-30 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_inventory_original_quantity_inventory_total_disposed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('loan_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('quantity_loaned', models.IntegerField()),
                ('quantity_returned', models.IntegerField(default=0)),
                ('quantity_sold', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('on_loan', 'On Loan to Pharmacy'), ('returned', 'Returned to Warehouse'), ('sold', 'Sold by Pharmacy')], default='on_loan', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory')),
            ],
        ),
    ]
